#task.name = main-task-ZADACHA
#task.duration=60
#
#list.values=123,234,345
#set.values = primer,strok,smotri
#
#map.values = {key1: 100, key2: 200}
#
#
#coffee.machine.name = SuperBarista 3000
#coffee.machine.default-bean-type=Arabica
#coffee.machine.water-temperature=92
#coffee.machine.quality-check-enabled=true
#
#
#coffee.notification.email=barista@coffeeshop.com
#coffee.notification.sms=+1234567890
#
#
#coffee.limits.daily-cups=100
#coffee.limits.warning-threshold=20
#
#

account.default.amount=1000.00
account.transfer.commission=10